version: '3.8'

services:
  chatbot:
    build: .
    container_name: chatbot
    depends_on:
      - mongo
      - redis
      - llama
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  llama:
    build:
      context: ./llamaapi
    container_name: llama
    ports:
      - "8001:8000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chatbot
    networks:
      - backend

networks:
  backend: